# Generated by Django 5.2.9 on 2026-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='grace_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='paid_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tenantpayment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
