# Generated by Django 5.2.9 on 2026-01-07 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='grace_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantpayment',
            name='reference',
            field=models.CharField(help_text='Unique payment reference from the payment provider ex: transaction id', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.subscriptionplan'),
        ),
    ]
