# Generated by Django 5.2.9 on 2026-01-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_subscriptionplan_tenant_grace_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantpayment',
            name='currency',
            field=models.CharField(default='ETB', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenantpayment',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenantpayment',
            name='reference',
            field=models.CharField(blank=True, help_text='Unique payment reference from the payment provider ex: transaction id', max_length=100, null=True, unique=True),
        ),
    ]
